### PR TITLE
Bug fixes

### LINKED ISSUE #65: Edit command does not detect duplicate projects if the created date is different
The command run in both images was `edit 1 n/b`. The only difference between the two project `a`'s is the created date.

image

image

Changing the created date makes the program avoid the following condition in `EditCommand.java`. 

image

Is this something that needs to be fixed?

### PR DESCRIPTION
**Pull request by boundtotheearth**
Fixed Active Timers to update automatically when projects are changed.
Also fixed the issue where created date is considered for isSameProject
Closes #65

### CODE REVIEW

**Review by khoodehui — APPROVED** [review]

File: src/main/java/seedu/momentum/model/ModelManager.java [hunk 1]
```diff
@@ -283,23 +275,16 @@ public void removeReminder() {
...
-        assert (trackedItem.isRunning());
-        assert (runningTimers.contains(trackedItem));
-
-        runningTimers.remove(trackedItem);
-        runningTimer = trackedItem;
-        toAdd = true;
+    /**
+     * Update the running timers list.
+     */
+    public void updateRunningTimers() {
```
Comment (kkangs0226) [inline src/main/java/seedu/momentum/model/ModelManager.java:284]: Is there a need to toggle toAdd boolean in this method?

**Review by kkangs0226 — APPROVED** [review]
